# configure client cred for keycloak ( for creating user )
keycloak:
  server-url: https://ite-keycloak.anajak-khmer.site 
  realm: ecommerce-realm
  client-id: springboot-app
  client-secret: CF1I9QYQM3ZcJLRShA3DwkmYndrnvmGe
file:
    client-path: /files
    storage-location: ite-images/
    base-url: http://localhost:${server.port}${file.client-path}/
# http://localhost:8080/files/
spring:
  # issuer is the realm in keycloak that we configure
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://ite-keycloak.anajak-khmer.site/realms/spring-app-realm
    servlet:
      multipart:
        max-file-size: 10MB # max allocation for single file size
        max-request-size: 30MB # ... for the whole request
#    security:
#      user:
#        name: developer
#        password: pass12345
    application:
      name: product-api-simple-demo
# jpa, postgres
    datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto:  update #  create-drop #update    # create | update | none
      show-sql: true          # log generated SQL
      properties:
        hibernate:
          format_sql: true
server:
  port: 8080
